//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Банковская_карта
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Банковская_карта()
        {
            this.Заказы = new HashSet<Заказы>();
        }
    
        public string Название_карты { get; set; }
        public int Номер_карта { get; set; }
        public string Владелец_карты { get; set; }
        public Nullable<int> Код_CVC { get; set; }
        public Nullable<System.DateTime> Срок_истечения_карты { get; set; }
    
        public virtual Покупатель Покупатель { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказы> Заказы { get; set; }
    }
}
