//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Детали_заказа
    {
        public int Код_детали_заказа { get; set; }
        public Nullable<int> Номер_заказа { get; set; }
        public Nullable<int> Товар { get; set; }
        public string Количество { get; set; }
    
        public virtual Заказы Заказы { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
