//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.Детали_заказа = new HashSet<Детали_заказа>();
        }
    
        public int Заказ { get; set; }
        public Nullable<int> Код_адреса { get; set; }
        public string Дата { get; set; }
        public Nullable<int> Код_покупателя { get; set; }
        public string Телефон_покупателя { get; set; }
        public string Оплата { get; set; }
        public Nullable<int> Код_сотрудника { get; set; }
        public Nullable<int> Номер_карты { get; set; }
        public string Стоимость_заказа { get; set; }
    
        public virtual Адрес_доставки Адрес_доставки { get; set; }
        public virtual Банковская_карта Банковская_карта { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Детали_заказа> Детали_заказа { get; set; }
    }
}
