//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Покупатель
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Покупатель()
        {
            this.Банковская_карта = new HashSet<Банковская_карта>();
        }
    
        public string Код_покупателя { get; set; }
        public string Ф { get; set; }
        public string И { get; set; }
        public string О { get; set; }
        public string E_mail { get; set; }
        public string Пол { get; set; }
        public string Дата_рождения { get; set; }
        public string Номер_карта { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Банковская_карта> Банковская_карта { get; set; }
    }
}
