//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товары()
        {
            this.Детали_заказа = new HashSet<Детали_заказа>();
        }
    
        public int Код_товара { get; set; }
        public Nullable<int> Код_категория { get; set; }
        public Nullable<int> Код_характеристики { get; set; }
        public Nullable<int> Код_поставщика { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Детали_заказа> Детали_заказа { get; set; }
        public virtual Категория_товара Категория_товара { get; set; }
        public virtual Поставщик Поставщик { get; set; }
        public virtual Характеристики_товара Характеристики_товара { get; set; }
    }
}
